sudo: required
language: go
go: '1.11'
env:
  global:
    - secure: "aWEHNogDWsinWVg5eYZkurKeNQx8hZXG3t04ojNABv3pW8luCDaVMm46AAYbLLNI5mvZw8NgJE33hEj+7riZU5I4z9FnO3WHFU0Ccqz/hco5dwh/ECBIHkmIa+LpKWPsybMiQVIHFUMto6FQjSlDh5LWoP48oPGQT7wRsVRMx4NKriNwHvmWOIKEPEpRFz4XN2IfyyQW0FaEkgLC8y8xl3R7MtdJG34ZktefYGws3mzgNJmSrW52WHgELh4juioxGNVgfYDdp85DoFRrP0OhOOpTL0Mir9PC0dkdThz5bncbePwm4WidNlkubjE7TbsMinpKmdqamML/nctivrGtZQ8Wg4viaJEKitcO7dsAHMv2pJxz9a15B0a7N0QkWaINJpQ6TfAuBFLKeqDq6zoJDdDZ3wjkg1wH+LirNQ7cdV6qH43eNF1yy0MdkGqf0DMe7Qkm79GYu6cKTKPYYR9QnooxjuBxVyhtvp2EToWzij7cItPQKYQbS9/vuIvJzV7keeO19aQB/vuazzOi9AJEyoM+YME9fVJdhX7mOod85LYlLosCcPzAvwNT1xLL5YU7aXEEQ0kR2vl8nIr0k0832wAKhvKg4O4MueSRyfJ8G1V29A2+B5MHsEGhYvPW0alHEOyEZKkTU2lxE9nAq3epW7sRIkt1Iv+hd6xSc0eMVuo="
    - secure: "ahdqfw2Zy6YCaj0GnZph/skqrDsUcJ5qagZ28tPP4Dxt1M9PRT4eV/66LN6umroJXz4sceK4nT6pCynlGEIxLnwh0x19c0z7IVhhDALfbnYZULfw36y5bmYA9VsKajl5JvZ22f46dAE/v8IwCi+gLuDA8xsf4Eu8x+0ivNFaBH+3KMZ2mnE/Uibwz+WB6Hz1044X9BvxfN9sNOHJO3lD3fsQI6KOjDImNJlYDNWgBaIx2QJcfn8ThQvlOYpcIrkzF8CG8kZM6+Mp4quV7iSugvWxLHbQDogVmXOy2LYb9E9jSo0ZztMikJQjMcMUTlrYVy6Qc5NIzBI8GS9F6JFgPxU3hiwjkm0bZasQ3UjLZQjcDd7TP+WQOx8Jqqy1DMpk0/I/wKlLwUyDTM5C0FGHwEmOk3K+MEDwuuRk88tExr2hUO8xrB3xzvg7BbCDa+zPQyf7Fy+kRAjen5Pp/XxHDi5UNn+3qm6XmXybysYKmF5eZrFI1bpHtJqCFpSZOUCQc6oDRASz7SZmbEEDUmMnJasji6gqK4MFsJTy8CdkdJBA6kMXGDiZqK0qugGDp2fGsEupwEwMD57zsqjzT1ijCLV4whMrX6q0oLtw0b5kXUL4OGctubvGAeATSEKfDNqt4pVupaxTNk3jPaJvTR/9ljXm9tc77wJy3tdp31Y5YoQ="

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
services:
- docker
jobs:
  include:
  - stage: ci-cd
    script: make ci
    before_deploy: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    if: tag IS blank
    deploy:
    - provider: script
      skip_cleanup: true
      script: make cd BRANCH_NAME=${TRAVIS_BRANCH}
  - stage: release
    before_deploy: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    if: tag IS NOT blank
    script: echo true
    deploy:
    - provider: script
      skip_cleanup: true
      script: make release
      on:
        tags: true
